override HOST_PRIMARY_ARCH := host_i386
override HOST_32BIT_ARCH := host_i386
override HOST_FORCE_32BIT := 
override TARGET_PRIMARY_ARCH := target_armhf
override TARGET_SECONDARY_ARCH := 
override TARGET_ALL_ARCH :=  target_armhf 
override TARGET_FORCE_32BIT := 
override KERNELDIR := /home/gatieme/Work/Arm/Board/cubieboard/cc-a80/cc-a80-linux-sdk/linux-3.4
override KERNEL_ID := 3.4.39
override KERNEL_COMPONENTS := srvkm dc_drmfbdev
override EXTRA_PVRSRVKM_COMPONENTS := dbgdrv
override KERNEL_CROSS_COMPILE := arm-linux-gnueabihf-
override PVRSRV_MODNAME := pvrsrvkm
override PVR_BUILD_DIR := sunxi_linux
override PVR_BUILD_TYPE := release
override DISPLAY_CONTROLLER := dc_drmfbdev
override PVR_SYSTEM := rgx_sunxi
override BUILD := release
override DEBUGLINK := 1
override CACHEFLUSH_TYPE := CACHEFLUSH_GENERIC
override PDUMP := 1
override SUPPORT_INSECURE_EXPORT := 1
override SUPPORT_SECURE_EXPORT := 1
override PVR_HANDLE_BACKEND := idr
override SUPPORT_DRM := 1
override SUPPORT_DRM_DC_MODULE := 1
