#!/bin/sh

MAC_ADDR="`uuidgen |awk -F- '{print $5}'|sed 's/../&:/g'|sed 's/\(.\)$//' |cut -b3-17`"

ifconfig eth0 hw ether "48$MAC_ADDR"
ifconfig lo 127.0.0.1
ifconfig eth0 192.168.1.123
#udhcpc -n -T 1 -t 3
